#
#
# This prevents:
# fatal error: opening dependency file drivers/thermal/intelli/.msm_thermal.o.d: No such file or directory
# error while building with adroid's gcc 4.8 toolchain (otherwise, builds nicely with Linaro 4.8?)
#

obj-$(CONFIG_INTELLI_THERMAL)	+= msm_thermal.o
